### ISSUE TITLE
Not working with WebdriverIO

### ISSUE THREAD

**Issue by owens-ben** [mgrybyk/mocha-qtest-mapping-reporter#8]
I thought this might be able to work with WebdriverIO, but I think I'm missing config somewhere.

in my config:

```
const qtest = require('mocha-qtest-mapping-reporter')
exports.config = {

 reporters: [
    'spec',
    [qtest,{options:{
      host: "https://xxxx.qtestnet.com/",
      bearerToken: "xx-xx-xx-xx-xx",
      projectId: "xxxxx",
      "statePassed": "PASS",
      "stateFailed": "FAIL",
      "enableLogs": true,
      "hideWarning": true,
      "hideResultUrl": false
    }}],
}
```

throws the error 

```[0-0] 2022-02-22T16:45:56.085Z ERROR @wdio/local-runner: Failed launching test session: TypeError: runner.on is not a function
[0-0]     at new qTest (/Users/eng7/git/xx-x-x/web/node_modules/mocha-qtest-mapping-reporter/index.js:226:12)
[0-0]     at BaseReporter.initReporter (/Users/eng7/git/xx-x-x/web/node_modules/@wdio/runner/build/reporter.js:135:20)
[0-0]     at Array.map (<anonymous>)
[0-0]     at new BaseReporter (/Users/eng7/git/Lively-Dev-Bundle/web/node_modules/@wdio/runner/build/reporter.js:22:50)
[0-0]     at Runner.run (/Users/eng7/git/xx-x-x/web/node_modules/@wdio/runner/build/index.js:77:26)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)```

**Comment by owens-ben** [comment]
Tried many different iterations of the config values but nothing is working.

**Comment by mgrybyk** [comment]
Hello, I'm not using the neither reporter nor qtest for a long time already. However, it looks like reporter initialization mechanism has changed in the newer versions of wdio.

Which version of webdriverio are you using?
Feel free to raise a PR with a fix, I can make you a mainter if you like.

Thank you

**Comment by owens-ben** [comment]
@mgrybyk wdio v 7.7.5

I'm afraid I don't know enough about it either to be of much help... It would be really nice to have this though. I am considering writing a custom one with only the very few functionalities I need (create new test run, mark existing tests as pass/fail).

I think my starting point would be the existing JUnit reporter, then parsing the XML and uploading the results.

**Comment by mgrybyk** [comment]
I think the fix should be quite trivial regarding the reporter initialization.
Not sure if other parts work well though.
I'll look into it on weekends
